---
title: "HNYC Cleaning"
author: "Kyi Yeung Goh"
date: "06/06/2019"
output: html_document
---

```{r setup, include=FALSE}
library(zoo)
library(magrittr)
library(dplyr)
library(tidyverse)
library(readxl)
library(stringr)
library(fuzzyjoin)
library(tm)
library(english)
library(reshape2)
df<-read_csv("us1910m_usa_sample10k.csv")
df2<-read_csv("us1910m_usa_sample100k.csv")
oldstreets1<-read_xlsx("OldStreets_StreetNames_CleanNotChecked.xlsx")
ed_descriptionMN<-read_xlsx("ED_descriptionsMN1910.xlsx")
manhattan_dan<-read_csv("mn_segments_export.csv")
sm_manhattan<-read_xlsx("SteveMorse_ManhattanStreets.xlsx") #upload
```


### NAMES SOURCE 1: DAN ED  **

### Create ED Dictionary
```{r}
EDict<-manhattan_dan%>%
  select("streets"=MN_STREET1910_FULL_STREE,"ED1"=MN_STREET1910_MINUS_ED_ED,"ED2"=MN_STREET1910_PLUS_ED_ED)

EDict1<-manhattan_dan%>%
  select("streets"=MN_STREET1910_Y1910NAMESTREET,"ED1"=MN_STREET1910_MINUS_ED_ED,"ED2"=MN_STREET1910_PLUS_ED_ED)

EDict2<-manhattan_dan%>%
  select("streets"=MN_STREET1910_Y1910NAMEALT,"ED1"=MN_STREET1910_MINUS_ED_ED,"ED2"=MN_STREET1910_PLUS_ED_ED)

EDict_MN<-rbind(EDict,EDict1,EDict2)

EDict_MN$cleaned<-EDict_MN$streets
EDict_MN$cleaned<-gsub("\\<ST\\>","STREET",EDict_MN$cleaned)
EDict_MN$cleaned<-gsub("\\<N\\>","NORTH",EDict_MN$cleaned)
EDict_MN$cleaned<-gsub("\\<S\\>","SOUTH",EDict_MN$cleaned)
EDict_MN$cleaned<-gsub("\\<E\\>","EAST",EDict_MN$cleaned)
EDict_MN$cleaned<-gsub("\\<W\\>","WEST",EDict_MN$cleaned)
EDict_MN$cleaned<-gsub("\\<DR\\>","DRIVE",EDict_MN$cleaned)
EDict_MN$cleaned<-gsub("\\<CIR\\>","CIRCLE",EDict_MN$cleaned)
EDict_MN$cleaned<-gsub("\\<AVE\\>","AVENUE",EDict_MN$cleaned)
EDict_MN$cleaned<-gsub("\\<CT\\>","COURT",EDict_MN$cleaned)
EDict_MN$cleaned<-gsub("\\<BLVD\\>","BOULEVARD",EDict_MN$cleaned)
EDict_MN$cleaned<-gsub("\\<ALY\\>","ALLEY",EDict_MN$cleaned)
EDict_MN$cleaned<-gsub("\\<PL\\>","PLACE",EDict_MN$cleaned)
EDict_MN$cleaned<-gsub("\\<PKWY\\>","PARKWAY",EDict_MN$cleaned)
EDict_MN$cleaned<-gsub("\\<APPR\\>","APPROACH",EDict_MN$cleaned)
EDict_MN$cleaned<-gsub("\\<TER\\>","TERRACE",EDict_MN$cleaned)
EDict_MN$cleaned<-gsub("\\<PLZ\\>","PLAZA",EDict_MN$cleaned)
EDict_MN$cleaned<-gsub("\\<LN\\>","LANE",EDict_MN$cleaned)
EDict_MN$cleaned<-gsub("\\<BRG\\>","BRIDGE",EDict_MN$cleaned)
EDict_MN$cleaned<-gsub("\\<HL\\>","HILL",EDict_MN$cleaned)
EDict_MN$cleaned<-gsub("\\<1ST\\>","FIRST",EDict_MN$cleaned)
EDict_MN$cleaned<-gsub("\\b1\\b","FIRST",EDict_MN$cleaned)
EDict_MN$cleaned<-gsub("\\<2ND\\>","SECOND",EDict_MN$cleaned)
EDict_MN$cleaned<-gsub("\\b2\\b","SECOND",EDict_MN$cleaned)
EDict_MN$cleaned<-gsub("\\<3RD\\>","THIRD",EDict_MN$cleaned)
EDict_MN$cleaned<-gsub("\\b3\\b","THIRD",EDict_MN$cleaned)
EDict_MN$cleaned<-gsub("\\<4TH\\>","FOURTH",EDict_MN$cleaned)
EDict_MN$cleaned<-gsub("\\b4\\b","FOURTH",EDict_MN$cleaned)
EDict_MN$cleaned<-gsub("\\<5TH\\>","FIFTH",EDict_MN$cleaned)
EDict_MN$cleaned<-gsub("\\b5\\b","FIFTH",EDict_MN$cleaned)
EDict_MN$cleaned<-gsub("\\<6TH\\>","SIEDict_MNTH",EDict_MN$cleaned)
EDict_MN$cleaned<-gsub("\\b6\\b","SIEDict_MNTH",EDict_MN$cleaned)
EDict_MN$cleaned<-gsub("\\<7TH\\>","SEVENTH",EDict_MN$cleaned)
EDict_MN$cleaned<-gsub("\\b7\\b","SEVENTH",EDict_MN$cleaned)
EDict_MN$cleaned<-gsub("\\<8TH\\>","EIGHTH",EDict_MN$cleaned)
EDict_MN$cleaned<-gsub("\\b8\\b","EIGHTH",EDict_MN$cleaned)
EDict_MN$cleaned<-gsub("\\<9TH\\>","NINTH",EDict_MN$cleaned)
EDict_MN$cleaned<-gsub("\\b9\\b","NINTH",EDict_MN$cleaned)
EDict_MN$cleaned<-gsub("\\<10TH\\>","TENTH",EDict_MN$cleaned)
EDict_MN$cleaned<-gsub("\\b10\\b","TENTH",EDict_MN$cleaned)
EDict_MN$cleaned<-gsub("\\<11TH\\>","ELEVENTH",EDict_MN$cleaned)
EDict_MN$cleaned<-gsub("\\b11\\b","ELEVENTH",EDict_MN$cleaned)
EDict_MN$cleaned<-gsub("\\<12TH\\>","TWELFTH",EDict_MN$cleaned)
EDict_MN$cleaned<-gsub("\\b12\\b","TWELFTH",EDict_MN$cleaned)
EDict_MN$cleaned<-gsub("\\<13TH\\>","THIRTEENTH",EDict_MN$cleaned)
EDict_MN$cleaned<-gsub("\\b13\\b","THIRTEENTH",EDict_MN$cleaned)
EDict_MN$cleaned<-str_remove(EDict_MN$cleaned,"STREET")

EDict_MN$ED1<-as.numeric(as.character(EDict_MN$ED1))
EDict_MN$ED2<-as.numeric(as.character(EDict_MN$ED2))
```

### Addressing issues with addresses 

### For 10k sample 
```{r}
ED_SAMPLE<-EDict_MN%>%
  filter(ED1 %in% (14)|ED2 %in% (14))%>%
  filter(streets!="NULL")%>%
  distinct(streets)%>%
  select(streets)

## Note EDs for Oak and Roosevelt are off in the pull
```


### Working with the 100k sample

### Fill-down first
```{r}
df2<-read_csv("us1910m_usa_sample100k.csv")
for (i in 1:ncol(df2)){
if (is.na(df2[1,i]) == FALSE ){
  df2[,i]=na.locf(df2[,i])}
  else {
  df2[,i]=df2[,i]
    }
}
```

## Household profiles
```{r}
not_all_na <- function(x) any(!is.na(x))
hhprofiles<-df2%>%
  filter(is.na(df2$`Dwelling sequence number`)==TRUE)%>% 
  select_if(not_all_na)
```


### Removing the household and then joining it with persons
```{r}

personprofile<-df2%>%
  filter(is.na(df2$`Consistent historical data person identifier`)==FALSE)

```


```{r}
### Address problems
df2$`Street address 2`<-na.locf(df2$`Street address 2`)

### Inconsistent streetnames
distinct_streets2<-personprofile%>%
  select(`Enumeration district 2`,`House number`,`Street address 2`,`Dwelling serial number`,`Dwelling serial number 2`,`Line Number`,`Line number 2`,`Microfilm page number 3`)%>%
  distinct(`Street address 2`,.keep_all=TRUE)

distinct_streets2$`Enumeration district 2`<-as.numeric(as.character(distinct_streets2$`Enumeration district 2`))

colnames(distinct_streets2)[3]<-"streets"
```

### Function to clean existing streetnames and create a new column, match using that and then drop it after

```{r}
## Preprocessing strings

rem_dup_word <- function(x){
x <- tolower(x)
paste(unique(trimws(unlist(strsplit(x,split=" ",fixed=F,perl=T)))),collapse = 
" ")
}

str_clean<-function(x){
  x$cleaned<-gsub("\\<SRT\\>","STREET",x$cleaned)
  x$cleaned<-gsub("\\<STR\\>","STREET",x$cleaned)
  x$cleaned<-gsub("\\<ST\\>","STREET",x$cleaned)
  x$cleaned<-gsub("\\<SST\\>","STREET",x$cleaned)
  x$cleaned<-gsub("\\<TREET\\>","STREET",x$cleaned)
  x$cleaned<-gsub("\\<cleaned\\>","STREET",x$cleaned)
  x$cleaned<-gsub("\\<SREET\\>","STREET",x$cleaned)
  x$cleaned<-gsub("\\<N\\>","NORTH",x$cleaned)
  x$cleaned<-gsub("\\<S\\>","SOUTH",x$cleaned)
  x$cleaned<-gsub("\\<E\\>","EAST",x$cleaned)
  x$cleaned<-gsub("\\<W\\>","WEST",x$cleaned)
  x$cleaned<-gsub("\\<DR\\>","DRIVE",x$cleaned)
  x$cleaned<-gsub("\\<CIR\\>","CIRCLE",x$cleaned)
  x$cleaned<-gsub("\\<AVE\\>","AVENUE",x$cleaned)
  x$cleaned<-gsub("\\<CT\\>","COURT",x$cleaned)
  x$cleaned<-gsub("\\<BLVD\\>","BOULEVARD",x$cleaned)
  x$cleaned<-gsub("\\<ALY\\>","ALLEY",x$cleaned)
  x$cleaned<-gsub("\\<PL\\>","PLACE",x$cleaned)
  x$cleaned<-gsub("\\<PKWY\\>","PARKWAY",x$cleaned)
  x$cleaned<-gsub("\\<APPR\\>","APPROACH",x$cleaned)
  x$cleaned<-gsub("\\<TER\\>","TERRACE",x$cleaned)
  x$cleaned<-gsub("\\<PLZ\\>","PLAZA",x$cleaned)
  x$cleaned<-gsub("\\<LN\\>","LANE",x$cleaned)
  x$cleaned<-gsub("\\<BRG\\>","BRIDGE",x$cleaned)
  x$cleaned<-gsub("\\<HL\\>","HILL",x$cleaned)
  x$cleaned<-gsub(".*\\((.*)\\).*", "\\1", x$cleaned)
  x$cleaned<-gsub("\\<1ST\\>","FIRST",x$cleaned)
  x$cleaned<-gsub("\\b1\\b","FIRST",x$cleaned)
  x$cleaned<-gsub("\\<2ND\\>","SECOND",x$cleaned)
  x$cleaned<-gsub("\\b2\\b","SECOND",x$cleaned)
  x$cleaned<-gsub("\\<3RD\\>","THIRD",x$cleaned)
  x$cleaned<-gsub("\\b3\\b","THIRD",x$cleaned)
  x$cleaned<-gsub("\\<4TH\\>","FOURTH",x$cleaned)
  x$cleaned<-gsub("\\b4\\b","FOURTH",x$cleaned)
  x$cleaned<-gsub("\\<5TH\\>","FIFTH",x$cleaned)
  x$cleaned<-gsub("\\b5\\b","FIFTH",x$cleaned)
  x$cleaned<-gsub("\\<6TH\\>","SIXTH",x$cleaned)
  x$cleaned<-gsub("\\b6\\b","SIXTH",x$cleaned)
  x$cleaned<-gsub("\\<7TH\\>","SEVENTH",x$cleaned)
  x$cleaned<-gsub("\\b7\\b","SEVENTH",x$cleaned)
  x$cleaned<-gsub("\\<8TH\\>","EIGHTH",x$cleaned)
  x$cleaned<-gsub("\\b8\\b","EIGHTH",x$cleaned)
  x$cleaned<-gsub("\\<9TH\\>","NINTH",x$cleaned)
  x$cleaned<-gsub("\\b9\\b","NINTH",x$cleaned)
  x$cleaned<-gsub("\\<10TH\\>","TENTH",x$cleaned)
  x$cleaned<-gsub("\\b10\\b","TENTH",x$cleaned)
  x$cleaned<-gsub("\\<11TH\\>","ELEVENTH",x$cleaned)
  x$cleaned<-gsub("\\b11\\b","ELEVENTH",x$cleaned)
  x$cleaned<-gsub("\\<12TH\\>","TWELFTH",x$cleaned)
  x$cleaned<-gsub("\\b12\\b","TWELFTH",x$cleaned)
  x$cleaned<-gsub("\\<13TH\\>","THIRTEENTH",x$cleaned)
  x$cleaned<-gsub("\\b13\\b","THIRTEENTH",x$cleaned)
  x$cleaned<-str_remove(x$cleaned,"STREET")
  x$cleaned<-gsub("\\d+\\ - *\\d*","",x$cleaned) #remove addresses
  x$cleaned<-gsub("\\d+\\ TO *\\d*","",x$cleaned) #remove addresses
  x$cleaned<-gsub("\\d+\\-\\d*", "", x$cleaned) #remove address
  x$cleaned<-gsub("(\\d)(ST|ND|RD|TH)\\b", "\\1", x$cleaned)
  x$cleaned<-gsub("\\bSTR\\b","", x$cleaned)
  x$cleaned<-gsub("\\bST\\b","", x$cleaned)
  x$cleaned<-gsub("\\bSTREET\\b","", x$cleaned)
  x$cleaned<-trimws(x$cleaned, "both")
}

for (i in 1:nrow(distinct_streets2)){
distinct_streets2$cleaned[i]<-toupper(rem_dup_word(distinct_streets2$streets[i]))
}

# create numbered list
distinct_streets2$cleaned<-str_clean(distinct_streets2)
colnames(distinct_streets2)[1]<-"ED"


## Get specific EDs
### Transforming ED into integers
ED_100k<-na.omit(as.data.frame(unique(df2$`Enumeration district 2`)))
ED_100k<-as.numeric(as.character(ED_100k[,1]))
ED_100k<-as.list(sub("^[0]+", "", ED_100k)) 

ED_SAMPLE<-EDict_MN%>%
  filter(ED1 %in% ED_100k|ED2 %in% ED_100k)%>%
  filter(streets!="NULL")%>%
  select(-c("streets"))

```

```{r}
### first find ED of concern for that observation then search if not existent then search ALL and note this occurence
### search range to extract dictionary

datalist = list()

for (i in 1:nrow(distinct_streets2)){
  
ED_SAMPLE<-EDict_MN%>%
  filter(ED1==distinct_streets2$ED[i]|ED2==distinct_streets2$ED[i])%>%
  filter(streets!="NULL")%>%
  select(-c("streets"))
  
  ALL_SAMPLE<-EDict_MN%>%
  filter(streets!="NULL")%>%
  select(-c("streets"))
  
  if (nrow(ED_SAMPLE)!=0){
check<-stringdist_join(distinct_streets2[i,], ED_SAMPLE, 
                           by = "cleaned", #must be named streets
                           mode = "left",
                           ignore_case = FALSE, 
                           method = "jw",  #jaro-winkler distance works best for this set, can be tuned.
                           max_dist = 1, 
                           distance_col = "dscore")%>%
  group_by(cleaned.x)%>%
  filter(dscore==min(dscore)) %>%
  head(1)

check$ED_correct<-"YES"

datalist[[i]]<-check
  }else{
check<-stringdist_join(distinct_streets2[i,], ALL_SAMPLE, 
                           by = "cleaned", #must be named streets
                           mode = "left",
                           ignore_case = FALSE, 
                           method = "jw",  #jaro-winkler distance works best for this set, can be tuned.
                           max_dist = 1, 
                           distance_col = "dscore")%>%
  group_by(cleaned.x)%>%
  filter(dscore==min(dscore)) %>%
  head(1)

check$ED_correct="NO"

datalist[[i]]<-check

  }
}

address_check<-do.call("rbind", datalist)

##write.csv(address_check,"address_check.csv")

address_check_flags<-address_check%>%
  filter(dscore>0.25)

##write.csv(address_check_flags,"address_check_flags.csv")

```

### Creating data dictionary using MN pull
```{r}
EDict_MN_NOTNULL<-EDict_MN%>%
  filter(streets!="NULL")%>%
  select(-c(cleaned))%>%
  dplyr::arrange(streets)%>%
  melt(., id.vars=c("streets"), variable.name="ED")%>%
  select(-c(ED))%>%
  distinct(streets,value)%>%
  dplyr::group_by(value)%>%
  dplyr::mutate(rn = paste0("V", 1:n()))%>%
  tidyr::spread(rn, streets)

colnames(EDict_MN_NOTNULL)[1]="ED"

EDict_MN_NOTNULL <- EDict_MN_NOTNULL[mixedorder(colnames(EDict_MN_NOTNULL))]

write.csv(EDict_MN_NOTNULL,"MN_EDDictionary.csv")
```

