---
title: "Dictionary check"
author: "Kyi Yeung Goh"
date: "16/07/2019"
output: html_document
---

```{r warning=FALSE}
library(zoo)
library(magrittr)
library(dplyr)
library(tidyverse)
library(openxlsx)
library(readxl)
library(stringr)
library(fuzzyjoin)
library(tm)
library(english)
library(reshape2)
library(gtools)
library(compare)
morse_mn1910<-read_csv("MN_MORSE_EDstreet_dict_1910.csv") 
morse_bk1910<-read_csv("BK_MORSE_EDstreet_dict_1910.csv")
mn_original<-read_csv("MN_EDDictionary.csv")
bk_original<-read_xlsx("BK_EDDictionary.xlsx")
```


```{r}
## convert to similar form as previous EDict
morse_mn1910<-as.data.frame(sapply(morse_mn1910, toupper)) 
morse_bk1910<-as.data.frame(sapply(morse_bk1910, toupper)) 

## joining frames
morse_mn1910$ED<-as.numeric(as.character(morse_mn1910$ED))
combined_edict_mn<-left_join(morse_mn1910,mn_original,by="ED")
combined_edict_mn<-combined_edict_mn%>%
  select(-X1)

## gather
combined_edict_mn<-gather(data = combined_edict_mn, 
             key = item, 
             value = value, 
             V1.x:V66)%>%
   select(-item)%>%
  group_by(ED)
combined_edict_mn<-na.omit(combined_edict_mn)
```


## clean strings
```{r}

str_clean_streets<-function(x){
  x$cleaned<-gsub("\\<SRT\\>$|\\<SR\\>$\\<SRT\\>$|\\<STR\\>$|\\<SST\\>$|\\<SEET\\>$|\\<TREET\\>$|\\<SHEER\\>$|\\<SHEE\\>$|\\<STREE\\>$|\\<SREET\\>$|\\<REET\\>$|\\<STEE\\>$|\\<ST\\>$","STREET",x$cleaned)
  x$cleaned<-gsub("\\<N\\>","NORTH",x$cleaned)
  x$cleaned<-gsub("\\<S\\>","SOUTH",x$cleaned)
  x$cleaned<-gsub("\\<E\\>","EAST",x$cleaned)
  x$cleaned<-gsub("\\<W\\>","WEST",x$cleaned)
  x$cleaned<-gsub("\\<DR\\>|\\<DV\\>|\\<DE\\>$|\\<DRV\\>|\\<DRI\\>|\\<DRIV\\>|\\<DRIE\\>","DRIVE",x$cleaned) 
  x$cleaned<-gsub("\\<CIR\\>|\\<CRL\\>|\\<CIRC\\>|\\<CR\\>|\\<CL\\>|\\<CIRCL\\>|\\<CICLE\\>","CIRCLE",x$cleaned)
  x$cleaned<-gsub("\\<AVE\\>|\\<AV\\>|\\<AVN\\>|\\<AVEN\\>|\\<AVENU\\>","AVENUE",x$cleaned)
  x$cleaned<-gsub("\\<CT\\>|\\<CRT\\>|\\<CTR\\>|\\<COUR\\>|\\<COT\\>|\\<CORT\\>","COURT",x$cleaned)
  x$cleaned<-gsub("\\<BLVD\\>|\\<BVLD\\>|\\<BV\\>|\\<BLD\\>|\\<BD\\>|\\<BL\\>|\\<BLV\\>","BOULEVARD",x$cleaned)
  x$cleaned<-gsub("\\<RD\\>|\\<RAD\\>|\\<ROD\\>","ROAD",x$cleaned)
  x$cleaned<-gsub("\\<ALY\\>|\\<AL\\>|\\<ALLY\\>|\\<ALEY\\>|\\<ALLE\\>|\\<AY\\>","ALLEY",x$cleaned)
  x$cleaned<-gsub("\\<PL\\>|\\<PLC\\>|\\<PLE\\>|\\<PC\\>|\\<PLAC\\>|\\<PLCE\\>|\\<PCE\\>","PLACE",x$cleaned)
  x$cleaned<-gsub("\\<PK\\>|\\<PRK\\>|\\<PRAK\\>|\\<PAK\\>","PARK",x$cleaned)
  x$cleaned<-gsub("\\<PKWY\\>|\\<PARKW\\>|\\<PWY\\>|\\<PKW\\>|\\<PRKWY\\>|\\<PKWY\\>|\\<PKW\\>","PARKWAY",x$cleaned)
  x$cleaned<-gsub("\\<APPR\\>|\\<APR\\>|\\<APPROA\\>|\\<APRCH\\>|\\<APPRCH\\>","APPROACH",x$cleaned)
  x$cleaned<-gsub("\\<TER\\>|\\<TERR\\>|\\<TRC\\>|\\<TRCE\\>|\\<TR\\>","TERRACE",x$cleaned)
  x$cleaned<-gsub("\\<PLZ\\>|\\<PLAZ\\>|\\<PZ\\>|\\<PLZA\\>","PLAZA",x$cleaned)
  x$cleaned<-gsub("\\<LN\\>|\\<LNE\\>|\\<LAN\\>","LANE",x$cleaned)
  x$cleaned<-gsub("\\<BRG\\>|\\<BRGD\\>|\\<BGE\\>","BRIDGE",x$cleaned)
  x$cleaned<-gsub("\\<HL\\>|\\<HLL\\>|\\<HIL\\>","HILL",x$cleaned)
  x$cleaned<-gsub("\\<HTS\\>|\\<HT\\>|\\<HEIGHT\\>|\\<HEGHTS\\>|\\<HHT\\>|\\<HEIGT\\>","HEIGHTS",x$cleaned) 
  x$cleaned<-gsub(".*\\((.*)\\).*", "\\1", x$cleaned)
  x$cleaned<-str_remove(x$cleaned,"STREET")
  x$cleaned<-gsub("\\d+\\ - *\\d*|\\d+\\ TO *\\d*|\\d+\\-\\d*","",x$cleaned) #remove addresses
  

  ## dealing with numbered streets
x$cleaned<-gsub("(\\d)(ST|ND|RD|TH)\\b", "\\1", x$cleaned)
x$cleaned<-str_remove(x$cleaned, "(?<=[0-9])(ST|ND|RD|TH)")
x$cleaned<-gsub("\\<ONE HUNDRED\\>|\\<ONEHUNDRED\\>|\\<HUNDRED\\>|\\<HUDRED\\>|\\<HUNDED\\>","1",x$cleaned) 
x$cleaned<-gsub("\\<TWO HUNDRED\\>|\\<TWOHUNDRED\\>","2",x$cleaned)
x$cleaned<-gsub("-"," ",x$cleaned)
x$cleaned<-gsub("\\<AND\\>"," ",x$cleaned)
x$cleaned<-gsub("&"," ",x$cleaned)
x$cleaned<-gsub("\\<1ST\\>|\\b1\\b","FIRST",x$cleaned)
x$cleaned<-gsub("\\<2ND\\>|\\b2\\b","SECOND",x$cleaned)
x$cleaned<-gsub("\\<3RD\\>|\\b3\\b","THIRD",x$cleaned)
x$cleaned<-gsub("\\<4TH\\>|\\b4\\b","FOURTH",x$cleaned)
x$cleaned<-gsub("\\<5TH\\>|\\b5\\b","FIFTH",x$cleaned)
x$cleaned<-gsub("\\<6TH\\>|\\b6\\b","SIXTH",x$cleaned)
x$cleaned<-gsub("\\<7TH\\>|\\b7\\b","SEVENTH",x$cleaned)
x$cleaned<-gsub("\\<8TH\\>|\\b8\\b","EIGHTH",x$cleaned)
x$cleaned<-gsub("\\<9TH\\>|\\b9\\b","NINTH",x$cleaned)
x$cleaned<-gsub("\\<10TH\\>|\\b10\\b","TENTH",x$cleaned)
x$cleaned<-gsub("\\<11TH\\>|\\b11\\b","ELEVENTH",x$cleaned)
x$cleaned<-gsub("\\<12TH\\>|\\b12\\b","TWELFTH",x$cleaned)
x$cleaned<-gsub("\\<13TH\\>|\\b13\\b","THIRTEENTH",x$cleaned)
x$cleaned<-gsub("\\<14TH\\>|\\b14\\b","FORTEENTH",x$cleaned)
x$cleaned<-gsub("\\<15TH\\>|\\b15\\b","FIFTEENTH",x$cleaned)
x$cleaned<-gsub("\\<16TH\\>|\\b16\\b","SIXTEENTH",x$cleaned)
x$cleaned<-gsub("\\<17TH\\>|\\b17\\b","SEVENTEENTH",x$cleaned)
x$cleaned<-gsub("\\<18TH\\>|\\b18\\b","EIGHTEENTH",x$cleaned)
x$cleaned<-gsub("\\<19TH\\>|\\b19\\b","NINETEENTH",x$cleaned)


x$cleaned<-gsub("\\<TWENTY\\>|\\<TWENTI\\>|\\<TENTI\\>","2",x$cleaned)
x$cleaned<-gsub("\\<THIRTY\\>|\\<THIRTHY\\>|\\<THIRTEY\\>|\\<TIRTY\\>|\\<TRITHY\\>","3",x$cleaned)
x$cleaned<-gsub("\\<FORTY\\>|\\<FOURTY\\>|\\<FOURTHY\\>|\\<FRTY\\>","4",x$cleaned)
x$cleaned<-gsub("\\<FIFTY\\>|\\<FIFTEY\\>|\\<FIFT\\>|\\<FITY\\>|\\<FIFTHY\\>","5",x$cleaned)
x$cleaned<-gsub("\\<SIXTY\\>|\\<SXTY\\>|\\<SIXY\\>|\\<SXTY\\>|\\<SIXTHY\\>|\\<SIXTEY\\>","6",x$cleaned)
x$cleaned<-gsub("\\<SEVENT\\>|\\<SEVENTY\\>|\\<SEVENTEY\\>|\\<SVENTY\\>|\\<SEVENTI\\>","7",x$cleaned)
x$cleaned<-gsub("\\<EIGHTY\\>|\\<EIGHTEY\\>|\\<EIGHTE\\>","8",x$cleaned)
x$cleaned<-gsub("\\<UNITY\\>|\\<NINTH\\>|\\<NINETY\\>|\\<NINETEY\\>|\\<NINETIETH\\>|\\<NINTY\\>","9",x$cleaned)
x$cleaned<-gsub("\\<FRIST\\>|\\<FIST\\>|\\<FRST\\>|\\<FIRST\\>|\\<ONE\\>","1",x$cleaned)
x$cleaned<-gsub("\\<SECOND\\>|\\<SECORD\\>|\\<SCOND\\>|\\<SECOND\\>|\\<TWO\\>","2",x$cleaned)
x$cleaned<-gsub("\\<THRID\\>|\\<THIRD\\>|\\<TIRD\\>|\\<TRIHD\\>|\\<THREE\\>","3",x$cleaned)
x$cleaned<-gsub("\\<FORTH\\>|\\<FOURTH\\>|\\<FROTH\\>|\\<FROUTH\\>|\\<FOUR\\>","4",x$cleaned)
x$cleaned<-gsub("\\<FIFETH\\>|\\<FIFTH\\>|\\<FIFFTH\\>|\\<FIFTHE\\>|\\<FIVE\\>","5",x$cleaned)
x$cleaned<-gsub("\\<SIXTH\\>|\\<SXTH\\>|\\<SITH\\>|\\<SIHXT\\>|\\<SIX\\>","6",x$cleaned)
x$cleaned<-gsub("\\<SEVENTH\\>|\\<SVEN\\>|\\<SVENTH\\>|\\<SEVENH\\>|\\<SEVENT\\>|\\<SEVEN\\>","7",x$cleaned)
x$cleaned<-gsub("\\<EIGHTH\\>|\\<EIGHTEH\\>|\\<EITH\\>|\\<EIGHT\\>","8",x$cleaned)
x$cleaned<-gsub("\\<NINETH\\>|\\<NINTH\\>|\\<NINT\\>|\\<NINETH\\>|\\<NINE\\>|\\<NIN\\>","9",x$cleaned)
x$cleaned<-gsub("\\<TWENTIETH\\>|\\<TWENTIEFTH\\>","20",x$cleaned) #NEW
x$cleaned<-gsub("\\<THIRTIETH\\>|\\<THIRTIEFTH\\>","30",x$cleaned)
x$cleaned<-gsub("\\<FORTIETH\\>|\\<FOURTIETH\\>","40",x$cleaned)
x$cleaned<-gsub("\\<FIFTIETH\\>","50",x$cleaned)
x$cleaned<-gsub("\\<SIXTIETH\\>","60",x$cleaned)
x$cleaned<-gsub("\\<SEVENTIETH\\>","70",x$cleaned)
x$cleaned<-gsub("\\<EIGHTIETH\\>","80",x$cleaned)
x$cleaned<-gsub("\\<NINETIETH\\>|\\<NINTIETH\\>","90",x$cleaned)
x$cleaned<-gsub("(?<=\\d) (?=\\d)","",x$cleaned,perl = T) #new close gaps between all numbers
## place names
  ##x$cleaned<-gsub("\\bSTR\\b","", x$cleaned)
  x$cleaned<-gsub("^\\bST\\b","SAINT", x$cleaned) 
  x$cleaned<-gsub("\\bHOUSE\\b","", x$cleaned)
  x$cleaned<-gsub("\\bHOSTEL\\b","", x$cleaned)
  x$cleaned<-gsub("\\bHOTEL\\b","", x$cleaned)
  x$cleaned<-gsub("\\bLODGE\\b","", x$cleaned)
  x$cleaned<-gsub("\\bLODGING\\b","", x$cleaned)
  x$cleaned<-trimws(x$cleaned, "both")
  x$cleaned<-gsub("\\<N\\>","NORTH",x$cleaned)
  ##x$cleaned<-gsub("\\<ST\\>","",x$cleaned)
  ##x$cleaned<-gsub("\\<STREET\\>","",x$cleaned)
} 
colnames(combined_edict_mn)[2]="streets"
```


```{r}
combined_edict_MN1<-combined_edict_mn%>%
  dplyr::arrange(streets)%>%
  melt(., id.vars=c("streets"), variable.name="ED")%>%
  select(-c(ED))%>%
  distinct(streets,value)%>%
  dplyr::group_by(value)%>%
  dplyr::mutate(rn = paste0("ED", 1:n()))%>%
  tidyr::spread(rn, streets)

colnames(combined_edict_MN1)[1]="ED"

combined_edict_MN1 <- combined_edict_MN1[mixedorder(colnames(combined_edict_MN1))]
write.csv(combined_edict_MN1,"combined_EDDictionary_MN.csv")

```

### Checking which are missing after cleaning
```{r}
morse_mn_list<-gather(data = morse_mn1910, 
             key = item, 
             value = value, 
             V1:V35)%>%
   select(-item)

morse_mn_list<-na.omit(morse_mn_list)
colnames(morse_mn_list)[2]<-"street"
morse_mn_list$street<-str_clean_streets(morse_mn_list)
morse_mn_list$source<-"morse"
morse_mn_list$street<-trimws(morse_mn_list$street,"both")

## Dan pull
geocoder_mn_list<-gather(data = mn_original, 
             key = item, 
             value = value, 
             V1:V66)%>%
   select(-X1)%>%
  select(-item)
geocoder_mn_list<-na.omit(geocoder_mn_list)
colnames(geocoder_mn_list)[2]<-"street"
geocoder_mn_list$street<-str_clean_streets(geocoder_mn_list)
geocoder_mn_list$source<-"geocoder"
geocoder_mn_list$street<-trimws(geocoder_mn_list$street,"both")


#left join 
missing_MN<-left_join(morse_mn_list,geocoder_mn_list, by=c("ED","street"))
missing_geocoder_MN<-missing_MN%>%
  filter(is.na(source.y)==TRUE)%>%
  select(-c(source.x,source.y))

missing_geocoder_MN<-missing_geocoder_MN%>%
  dplyr::arrange(street)%>%
  melt(., id.vars=c("street"), variable.name="ED")%>%
  select(-c(ED))%>%
  distinct(street,value)%>%
  dplyr::group_by(value)%>%
  dplyr::mutate(rn = paste0("V", 1:n()))%>%
  tidyr::spread(rn, street)
colnames(missing_geocoder_MN)[1]="ED"

missing_geocoder_MN <- missing_geocoder_MN[mixedorder(colnames(missing_geocoder_MN))]
#write.csv(missing_geocoder_MN,"missing_geocoder_MN.csv")

missing_ED<-left_join(morse_mn_list,geocoder_mn_list,by="ED")
missing_ED_MN<-missing_ED%>%
  filter(is.na(street.y)==TRUE)
#write.csv(missing_ED_MN,"missing_geocoder_MN_completeEDs.csv")
```



### For BK
```{r}
## joining frames
morse_bk1910$ED<-as.numeric(as.character(morse_bk1910$ED))
combined_edict_bk<-left_join(morse_bk1910,bk_original,by="ED")
combined_edict_bk<-combined_edict_bk

## gather
combined_edict_bk<-gather(data = combined_edict_bk, 
                          key = item, 
                          value = value, 
                          V1.x:V93)%>%
  select(-item)%>%
  group_by(ED)
combined_edict_bk<-na.omit(combined_edict_bk)
colnames(combined_edict_bk)[2]="streets"

```


```{r}
combined_edict_bk1<-combined_edict_bk%>%
  dplyr::arrange(streets)%>%
  melt(., id.vars=c("streets"), variable.name="ED")%>%
  select(-c(ED))%>%
  distinct(streets,value)%>%
  dplyr::group_by(value)%>%
  dplyr::mutate(rn = paste0("ED", 1:n()))%>%
  tidyr::spread(rn, streets)

colnames(combined_edict_bk1)[1]="ED"

combined_edict_bk1 <- combined_edict_bk1[mixedorder(colnames(combined_edict_bk1))]
##write.xlsx(combined_edict_bk1,"combined_EDDictionary_BK.xlsx")

```

### Checking which are missing after cleaning
```{r}
morse_mn_list<-gather(data = morse_mn1910, 
             key = item, 
             value = value, 
             V1:V35)%>%
   select(-item)

morse_mn_list<-na.omit(morse_mn_list)
colnames(morse_mn_list)[2]<-"street"
morse_mn_list$street<-str_clean_streets(morse_mn_list)
morse_mn_list$source<-"morse"
morse_mn_list$street<-trimws(morse_mn_list$street,"both")

## Dan pull
geocoder_mn_list<-gather(data = mn_original, 
             key = item, 
             value = value, 
             V1:V66)%>%
   select(-X1)%>%
  select(-item)
geocoder_mn_list<-na.omit(geocoder_mn_list)
colnames(geocoder_mn_list)[2]<-"street"
geocoder_mn_list$street<-str_clean_streets(geocoder_mn_list)
geocoder_mn_list$source<-"geocoder"
geocoder_mn_list$street<-trimws(geocoder_mn_list$street,"both")


#left join 
missing_MN<-left_join(morse_mn_list,geocoder_mn_list, by=c("ED","street"))
missing_geocoder_MN<-missing_MN%>%
  filter(is.na(source.y)==TRUE)%>%
  select(-c(source.x,source.y))

missing_geocoder_MN<-missing_geocoder_MN%>%
  dplyr::arrange(street)%>%
  melt(., id.vars=c("street"), variable.name="ED")%>%
  select(-c(ED))%>%
  distinct(street,value)%>%
  dplyr::group_by(value)%>%
  dplyr::mutate(rn = paste0("V", 1:n()))%>%
  tidyr::spread(rn, street)
colnames(missing_geocoder_MN)[1]="ED"

missing_geocoder_MN <- missing_geocoder_MN[mixedorder(colnames(missing_geocoder_MN))]
#write.csv(missing_geocoder_MN,"missing_geocoder_MN.csv")

missing_ED<-left_join(morse_mn_list,geocoder_mn_list,by="ED")
missing_ED_MN<-missing_ED%>%
  filter(is.na(street.y)==TRUE)
#write.csv(missing_ED_MN,"missing_geocoder_MN_completeEDs.csv")
```

## For Brooklyn
```{r}
## joining frames
morse_bk1910$ED<-as.numeric(as.character(morse_bk1910$ED))
combined_edict_bk<-left_join(morse_bk1910,bk_original,by="ED")

## gather
combined_edict_bk<-gather(data = combined_edict_bk, 
                          key = item, 
                          value = value, 
                          V1.x:V93)%>%
  select(-item)%>%
  group_by(ED)
combined_edict_bk<-na.omit(combined_edict_bk)


colnames(combined_edict_bk)[2]="streets"

```


```{r}
combined_edict_bk1<-combined_edict_bk%>%
  dplyr::arrange(streets)%>%
  melt(., id.vars=c("streets"), variable.name="ED")%>%
  select(-c(ED))%>%
  distinct(streets,value)%>%
  dplyr::group_by(value)%>%
  dplyr::mutate(rn = paste0("ED", 1:n()))%>%
  tidyr::spread(rn, streets)

colnames(combined_edict_bk1)[1]="ED"

combined_edict_bk1 <- combined_edict_bk1[mixedorder(colnames(combined_edict_bk1))]
##write.xlsx(combined_edict_bk1,"combined_EDDictionary_bk.xlsx")

```


### Checking which are missing after cleaning
```{r}
morse_bk_list<-gather(data = morse_bk1910, 
                      key = item, 
                      value = value, 
                      V1:V72)%>%
  select(-item)

morse_bk_list<-na.omit(morse_bk_list)
colnames(morse_bk_list)[2]<-"street"
morse_bk_list$street<-str_clean_streets(morse_bk_list)
morse_bk_list$source<-"morse"
morse_bk_list$street<-trimws(morse_bk_list$street,"both")

## Dan pull
geocoder_bk_list<-gather(data = bk_original, 
                         key = item, 
                         value = value, 
                         V1:V93)%>%
  select(-item)
geocoder_bk_list<-na.omit(geocoder_bk_list)
colnames(geocoder_bk_list)[2]<-"street"
geocoder_bk_list$street<-str_clean_streets(geocoder_bk_list)
geocoder_bk_list$source<-"geocoder"
geocoder_bk_list$street<-trimws(geocoder_bk_list$street,"both")

#left join 
missing_bk<-left_join(morse_bk_list,geocoder_bk_list, by=c("ED","street"))
missing_geocoder_bk<-missing_bk%>%
  filter(is.na(source.y)==TRUE)%>%
  select(-c(source.x,source.y))

missing_geocoder_bk<-missing_geocoder_bk%>%
  dplyr::arrange(street)%>%
  melt(., id.vars=c("street"), variable.name="ED")%>%
  select(-c(ED))%>%
  distinct(street,value)%>%
  dplyr::group_by(value)%>%
  dplyr::mutate(rn = paste0("V", 1:n()))%>%
  tidyr::spread(rn, street)
colnames(missing_geocoder_bk)[1]="ED"

missing_geocoder_bk <- missing_geocoder_bk[mixedorder(colnames(missing_geocoder_bk))]
#write.csv(missing_geocoder_bk,"missing_geocoder_bk.csv")

missing_ED<-left_join(morse_bk_list,geocoder_bk_list,by="ED")
missing_ED_bk<-missing_ED%>%
  filter(is.na(street.y)==TRUE)
#write.csv(missing_ED_bk,"missing_geocoder_bk_completeEDs.csv")
```

