---
title: "Yuelin's split code"
output: html_document
---
#### Import all packages
```{r setup}
library(hunspell)
library(tidyverse)
library(fuzzyjoin)
```
#### Clean House Number Dictionary Function (Step 4A)
```{r 04_1_clean_hn_dict}
clean_hn_dict <- function(file) {
  
  fix_order <- function(str) {
    if (str == "NA?NA") {return (NA_character_)}
    
    str_split(str, "\\?") %>% 
      unlist() %>% 
      as.integer() %>%
      sort() %>% 
      str_c(collapse = "?")
  }
  
  hn_dict <- hn_dict %>%
    mutate(ED = str_pad(ED, 4, "left", pad = "0")) %>%
    select(ED, Name, Left_Low, Left_High, Right_Low, Right_High) %>%
    unite(col = "Left", Left_Low, Left_High, sep = "?") %>% 
    unite(col = "Right", Right_Low, Right_High, sep = "?") %>%
    rowwise() %>%
    mutate(Left = fix_order(Left), Right = fix_order(Right)) %>%
    ungroup() %>%
    gather(key = "column", value = "value", -c(ED, Name)) %>% 
    separate(col = value, into = c("Low", "High"), sep = "\\?") %>%
    mutate(Low = as.integer(Low), High = as.integer(High))
}
```
#### Import data
```{r import data, warning = FALSE}
#edict <- read_csv("~/Desktop/HNYC_census_processing/hnyc_census-master/Data/full_bk_dict1880.csv")
sample <- read_csv("/Users/olivia/Documents/GitHub/hnyc_census/1880/census_1880_h_mn_sample100k.csv")
#hn_dict <- read_csv("~/Desktop/HNYC_census_processing/hnyc_census-master/Data/combine_bk1880.csv")
#hn_dict <- hn_dict %>% clean_hn_dict()
```
```{r}
sample
```
#Now split the last column
#### Clean Name of Columns
```{r}
## clean column names: adapt code if sample has different columns. At minimum, ensure `record`, `ED` and `street_add` columns exist after cleaning.
# names(sample) <- c("record", "township", "county", "ED", "person_id",
#                   "dwelling_seq", "dwelling_ser", "dwelling_ser2", "hh_seq", "hh_seq_8",
#                   "hh_ser2", "hh_ser_bef_split", "indiv_seq", "split",
#                   "line_no", "line_no2", "microfilm",
#                   "n_fam", "n_person_bef_split", "house_num", "street_add")
names(sample) <- c("record", "year", "dwelling_ser", "dwsize", 
                   "township", "pageno", 
                   "microfilm", "n_fam", "hh_ser_bef_split", "split", "mcd", 
                   "county", "ED", "supdist",
                   "street_add")
```
<br>
#Now split the last column
```{r}
sample <- sample %>% 
  separate(street_add, 
                c("house_num", "street", "type"))
sample
```
```{r}
sample$street1 <- paste(sample$street, sample$type)
sample
```
```{r}
sample2 = subset(sample, select = -c(street,type) )
sample2
```
```{r}
names(sample2) <- c("record", "year", "dwelling_ser", "dwsize", 
                   "township", "pageno", 
                   "microfilm", "n_fam", "hh_ser_bef_split", "split", "mcd", 
                   "county", "ED", "supdist", "house_num",
                   "street_add")
sample2
```
```{r}
write.csv(sample2, file = "census_1880_h_bk_split.csv")
```

```{r, echo=FALSE}
library(tidyr)
library(knitr)
library(kableExtra)
```
```{r}
sample_split <- read.csv("/Users/olivia/Documents/GitHub/hnyc_census/1880/Scripts/census_1880_h_bk_split.csv")

household1 <- filter(sample_split, record == "H")

tibble(none = nrow(filter(household1, is.na(house_num) & is.na(street_add))),
       only_house = nrow(filter(household1, !is.na(house_num) & is.na(street_add))),
       only_street = nrow(filter(household1, is.na(house_num) & !is.na(street_add))),
       both = nrow(filter(household1, !is.na(house_num) & !is.na(street_add)))) %>%
  kable() %>% kable_styling(full_width = FALSE)
```


