---
title: "Adaptive Jump Sizes EDA"
author: "Jolene Lim"
date: "26 February 2020"
output: html_document
---

This EDA looks at how we may implement adaptive jump_sizes for use in getSequence and mergeSequence

```{r, include=FALSE}
library(tidyverse)
sample <- readRDS("../Data/100k_post_clean.RDS")
```

We will look at the average differences in sequences of house numbers.

# 2 digit
```{r}
sample %>%
  filter(!is.na(hn_1) & hn_1 < 100) %>%
  pull(hn_1) %>%
  diff() %>%
  .[which(. != 0)] %>% # remove constant sequences bc this is not useful
  abs() %>%
  summary()
```

# 3 digit
```{r}
sample %>%
  filter(!is.na(hn_1) & str_length(hn_1) == 3) %>%
  pull(hn_1) %>%
  diff() %>%
  .[which(. != 0)] %>% # remove constant sequences bc this is not useful
  abs() %>%
  summary()
```

# 4 digit
```{r}
sample %>%
  filter(!is.na(hn_1) & str_length(hn_1) == 4) %>%
  pull(hn_1) %>%
  diff() %>%
  .[which(. != 0)] %>% # remove constant sequences bc this is not useful
  abs() %>%
  summary()
```

