---
title: "HYNC Cleaning 100k (House No.)"
author: "Kyi Yeung Goh"
date: "23/07/2019"
output: html_document
---

```{r setup, include=FALSE}
library(zoo)
library(dplyr)
library(tidyverse)
library(readxl)
library(stringr)
library(fuzzyjoin)
library(reshape2)
library(data.table)
df2<-read_csv("us1910m_usa_sample100k.csv")
```

## Extract house address column to check distinct
### Fill-down first
```{r}
df2<-read_csv("us1910m_usa_sample100k.csv")
for (i in 1:ncol(df2)){
if (is.na(df2[1,i]) == FALSE ){
  df2[,i]=na.locf(df2[,i])}
  else {
  df2[,i]=df2[,i]
    }
}
```

## Household profiles
```{r warning=FALSE}
not_all_na <- function(x) any(!is.na(x))
hhprofiles<-df2%>%
  dplyr::filter(is.na(df2$`Dwelling sequence number`)==TRUE)%>% 
  select_if(not_all_na)

distinct_no<-hhprofiles%>%
  select(`House number`,`Street address 2`,`Household serial number 2`)%>%
  distinct(`House number`,`Street address 2`,`Household serial number 2`)%>%
  dplyr::mutate(original_no=`House number`)

## extract out patterns from street addresses as well and override in cases where they clash
for (i in 1:nrow(distinct_no)){
  if (str_detect(distinct_no$`Street address 2`[i],"\\d+\\ - *\\d*|\\d+\\ TO *\\d*|\\d+\\-\\d*")==TRUE){
distinct_no$`House number`[i]<-str_extract(distinct_no$`Street address 2`[i], "\\d+\\ - *\\d*|\\d+\\ TO *\\d*|\\d+\\-\\d*")
  }else{
  distinct_no$`House number`[i]<-distinct_no$`House number`[i]
  }
}

colnames(distinct_no)[1]="house_no"
distinct_no$house_no<-gsub("\\<1/2\\>",".5",distinct_no$house_no) #exact match on 1/2
distinct_no$house_no<-gsub("\\b .\\b",".",distinct_no$house_no) #convert 1/2 to .5

## dealing with numbers
distinct_no$number<-gsub("\\b TO \\b|\\bTO\\b|\\b & \\b|\\b&\\b|\\b AND \\b|\\bAND\\b","-",distinct_no$house_no)
distinct_no$number<-gsub(" ","-",distinct_no$number)
distinct_no$number<-gsub("/","-",distinct_no$number) 
distinct_no$house_words<-gsub("[^[:alpha:]]", "", distinct_no$house_no)
distinct_no$number<-gsub("[[:space:]]", "", distinct_no$number)
distinct_no$number<-gsub("[^0-9.-]", "", distinct_no$number)
distinct_no$number<-gsub("^\\-\\b","", distinct_no$number) #remove front loose em-deshes
distinct_no$number<-gsub("-$", "",  distinct_no$number) #remove back hanging em-dashes
distinct_no$number<-gsub("-$", "",  distinct_no$number) #remove back hanging em-dashes from those with multiple entries
distinct_no$number<-gsub("-$", "",  distinct_no$number)#remove back hanging em-dashes from those with multiple entries

## split springs and repeat if they are the same 
setDT(distinct_no)[, paste0("number", 1:3) := tstrsplit(number, "-")]

## dealing with words- think alongside streetnames, bring in cleaned street names
colnames(distinct_no)[2]<-"streets"
colnames(distinct_no)[4]<-"House number"
df_cleaned_mn<-read_csv("100ksample_MN_matched.csv")
df_mn_numstreet<-left_join(df_cleaned_mn,distinct_no,by=c("House number","streets","Household serial number 2")) #joins cleaned house numbers with the cleaned addresses

```

```{r}
### REMEMBER TO INSERT HH IDENTIFICATION NO. SO THAT IT CAN MATCH
## what do I do with the ranges? 

### FOR NON-BLANK entries

###  (i) if streets match in previous or after AND (iia) difference between first number is greater than (abs) 500 then replace numbers with previous numbers OR if (iib) if the difference between the two entries is exactly the same as the previous entry (which implies a NULL) then take the number of the previous row AND (iii) drop decimal points

hhprofiles1<-df_mn_numstreet%>%
  dplyr::filter(is.na(df2$`Dwelling sequence number`)==TRUE)%>%
  select_if(not_all_na)%>%
  dplyr::select(house_no,streets,ED_streetname,corrected_str,number1,number2,number3,house_words)
#%>%distinct(house_no,streets,.keep_all = TRUE) #remove this line if you do not want to consider a smaller sample - runtime might be much longer

hhprofiles1$number1<-as.numeric(as.character(hhprofiles1$number1))
hhprofiles1$number1[is.na(hhprofiles1$number1)] <- 0
hhprofiles1$number2<-as.numeric(as.character(hhprofiles1$number2))
hhprofiles1$number2[is.na(hhprofiles1$number2)] <- 0
hhprofiles1$number3<-as.numeric(as.character(hhprofiles1$number3))
hhprofiles1$number3[is.na(hhprofiles1$number3)] <- 0

hhprofiles1$replaceno<-hhprofiles1$house_words #initiate new column to check replacement

## replace first 
for (i in 2:(nrow(hhprofiles1)-1)){ #first and last cannot be compared so remove them from algo
  if (((identical(hhprofiles1$corrected_str[i],hhprofiles1$corrected_str[i-1])&abs(hhprofiles1$number1[i]-hhprofiles1$number1[i-1])>500))==TRUE){ #if address same as before and difference between the two numbers is greater than 500
    hhprofiles1$number1[i]<-hhprofiles1$number1[i-1]
    hhprofiles1$number2[i]<-hhprofiles1$number2[i-1]
    hhprofiles1$number3[i]<-hhprofiles1$number3[i-1]
    hhprofiles1$replaceno[i]<-"YES"
  }else if(((identical(hhprofiles1$corrected_str[i-1],hhprofiles1$corrected_str[i+1])&(is.na(hhprofiles1$house_no[i]))))==TRUE){ # previous/after address are the same then take avg if initial is NA
    hhprofiles1$number1[i]<-(hhprofiles1$number1[i+1]+hhprofiles1$number1[i-1])/2
    hhprofiles1$number2[i]<-(hhprofiles1$number2[i+1]+hhprofiles1$number2[i-1])/2
    hhprofiles1$number3[i]<-(hhprofiles1$number3[i+1]+hhprofiles1$number3[i-1])/2
    hhprofiles1$replaceno[i]<-"YES BETWEEN" #between look
  }else if(((identical(hhprofiles1$corrected_str[i],hhprofiles1$corrected_str[i-1])&(hhprofiles1$number1[i]-hhprofiles1$number1[i-1])==-(hhprofiles1$number1[i-1])))==TRUE){ #if previous address is the same then take previous entry 
    hhprofiles1$number1[i]<-hhprofiles1$number1[i-1]
    hhprofiles1$number2[i]<-hhprofiles1$number2[i-1]
    hhprofiles1$number3[i]<-hhprofiles1$number3[i-1]
    hhprofiles1$replaceno[i]<-"YES"
  }else if(((identical(hhprofiles1$corrected_str[i],hhprofiles1$corrected_str[i+1])&(hhprofiles1$number1[i]-hhprofiles1$number1[i+1])==-(hhprofiles1$number1[i+1])))==TRUE){ 
    hhprofiles1$number1[i]<-hhprofiles1$number1[i+1]
    hhprofiles1$number2[i]<-hhprofiles1$number2[i+1]
    hhprofiles1$number3[i]<-hhprofiles1$number3[i+1]
    hhprofiles1$replaceno[i]<-"YES" 
  }else{
    hhprofiles1$number1[i]<-hhprofiles1$number1[i]
    hhprofiles1$number2[i]<-hhprofiles1$number2[i]
    hhprofiles1$number3[i]<-hhprofiles1$number3[i]
    hhprofiles1$replaceno[i]<-"NO"
  }
}

### Check first string 
if ((identical(hhprofiles1$corrected_str[1],hhprofiles1$corrected_str[2])&(is.na(hhprofiles1$house_no)))==TRUE){
    hhprofiles1$number1[1]<-hhprofiles1$number1[2]
    hhprofiles1$number2[1]<-hhprofiles1$number2[2]
    hhprofiles1$number3[1]<-hhprofiles1$number3[2]
    hhprofiles1$replaceno[1]<-"YES" 
} else if((identical(hhprofiles1$corrected_str[1],hhprofiles1$corrected_str[2])&(is.na(hhprofiles1$house_no)))==FALSE){
    hhprofiles1$number1[1]<-0
    hhprofiles1$number2[1]<-0
    hhprofiles1$number3[1]<-0
    hhprofiles1$replaceno[1]<-"YES" 
} else if (((identical(hhprofiles1$corrected_str[1],hhprofiles1$corrected_str[2])&abs(hhprofiles1$number1[1]-hhprofiles1$number1[2])>500))==TRUE){
    hhprofiles1$number1[1]<-hhprofiles1$number1[2]
    hhprofiles1$number2[1]<-hhprofiles1$number2[2]
    hhprofiles1$number3[1]<-hhprofiles1$number3[2]
    hhprofiles1$replaceno[1]<-"YES" 
} else{
    hhprofiles1$number1[1]<-hhprofiles1$number1[1]
    hhprofiles1$number2[1]<-hhprofiles1$number2[1]
    hhprofiles1$number3[1]<-hhprofiles1$number3[1]
    hhprofiles1$replaceno[1]<-"NO"
}

## check last string
if ((identical(hhprofiles1$corrected_str[nrow(hhprofiles)],hhprofiles1$corrected_str[nrow(hhprofiles1)-1])&(is.na(hhprofiles1$house_no)))==TRUE){
  hhprofiles1$number1[nrow(hhprofiles1)]<-hhprofiles1$number1[nrow(hhprofiles1)-1]
  hhprofiles1$number2[nrow(hhprofiles1)]<-hhprofiles1$number2[nrow(hhprofiles1)-1]
  hhprofiles1$number3[nrow(hhprofiles1)]<-hhprofiles1$number3[nrow(hhprofiles1)-1]
  hhprofiles1$replaceno[nrow(hhprofiles1)]<-"YES" 
} else if((identical(hhprofiles1$corrected_str[nrow(hhprofiles1)],hhprofiles1$corrected_str[nrow(hhprofiles1)-1])&(is.na(hhprofiles1$house_no)))==FALSE){
  hhprofiles1$number1[nrow(hhprofiles1)]<-0
  hhprofiles1$number2[nrow(hhprofiles1)]<-0
  hhprofiles1$number3[nrow(hhprofiles1)]<-0
  hhprofiles1$replaceno[nrow(hhprofiles)]<-"YES" 
} else if (((identical(hhprofiles1$corrected_str[nrow(hhprofiles1)],hhprofiles1$corrected_str[nrow(hhprofiles1)-1])&abs(hhprofiles1$number1[nrow(hhprofiles1)]-hhprofiles1$number1[nrow(hhprofiles1)-1])>500))==TRUE){
  hhprofiles1$number1[nrow(hhprofiles1)]<-hhprofiles1$number1[nrow(hhprofiles1)-1]
  hhprofiles1$number2[nrow(hhprofiles1)]<-hhprofiles1$number2[nrow(hhprofiles1)-1]
  hhprofiles1$number3[nrow(hhprofiles1)]<-hhprofiles1$number3[nrow(hhprofiles1)-1]
  hhprofiles1$replaceno[nrow(hhprofiles1)]<-"YES" 
} else{
  hhprofiles1$number1[nrow(hhprofiles1)]<-hhprofiles1$number1[nrow(hhprofiles1)]
  hhprofiles1$number2[nrow(hhprofiles1)]<-hhprofiles1$number2[nrow(hhprofiles1)]
  hhprofiles1$number3[nrow(hhprofiles1)]<-hhprofiles1$number3[nrow(hhprofiles1)]
  hhprofiles1$replaceno[nrow(hhprofiles1)]<-"NO"
}


## if null and match = then take next/ previous
## if null and don't match = 0
## if match but large difference


### ODD EVEN LABEL
hhprofiles1<-hhprofiles1%>%
  dplyr::mutate(oddeven=trunc(number1))
hhprofiles1$oddeven<-trunc(hhprofiles1$number1) ## truncate first number

## odd even shorthand function
is.even <- function(x) x %% 2 == 0
hhprofiles1$oddeven<- as.numeric(as.character(hhprofiles1$oddeven))


### assign odd or even labels
for (i in 1:(nrow(hhprofiles1))){
  if ((hhprofiles1$oddeven[i]==0)==TRUE){
    hhprofiles1$isoddeven[i]<-"NA"
  }else if (is.even(hhprofiles1$oddeven[i])==TRUE){
    hhprofiles1$isoddeven[i]<-"EVEN"
  }else{
    hhprofiles1$isoddeven[i]<-"ODD"
  }
}

###if string is YES between AND previous and after match AND current and previous do not then + 1 and replace it with isoddeven from previous string 
###if string is YES between and previous and after DO NOT match then DO NOTHING 
### else do nothing
### this is done to ensure that replaced house number are on same side of street
for (i in 2:(nrow(hhprofiles1)-1)){ 
  if ((((hhprofiles1$replaceno[i]=="YES BETWEEN")==TRUE)&(identical(hhprofiles1$isoddeven[i+1],hhprofiles1$isoddeven[i-1])==TRUE)&(identical(hhprofiles1$isoddeven[i],hhprofiles1$isoddeven[i-1])==FALSE))==TRUE){
    hhprofiles1$number1[i]<-(hhprofiles1$number1[i])+1
    hhprofiles1$isoddeven[i]<-hhprofiles1$isoddeven[i-1]
  } else if ((((hhprofiles1$replaceno[i]=="YES BETWEEN")==TRUE)&(identical(hhprofiles1$isoddeven[i+1],hhprofiles1$isoddeven[i-1])==FALSE))==TRUE){
    hhprofiles1$number1[i]<-hhprofiles1$number1[i]
    hhprofiles1$isoddeven[i]<-hhprofiles1$isoddeven[i]
  } else{
    hhprofiles1$number1[i]<-hhprofiles1$number1[i]
    hhprofiles1$isoddeven[i]<-hhprofiles1$isoddeven[i]
  }
}

### deal with multiple NAs one after another being 1/2-ed ### MATCH ON ADDRESS AS WELL
for (i in 2:(nrow(hhprofiles1)-1)){ 
  if (((is.na(hhprofiles1$house_no[i])&is.na(hhprofiles1$house_no[i-1]))==FALSE)&is.na(hhprofiles1$house_no[i])==TRUE&(identical(hhprofiles1$corrected_str[i],hhprofiles1$corrected_str[i-1])==TRUE)){
  hhprofiles1$number1[i]<-hhprofiles1$number1[i-1]
  hhprofiles1$number2[i]<-hhprofiles1$number2[i-1]
  hhprofiles1$number3[i]<-hhprofiles1$number3[i-1]
  }else if ((is.na(hhprofiles1$house_no[i])&is.na(hhprofiles1$house_no[i-1])&(identical(hhprofiles1$corrected_str[i],hhprofiles1$corrected_str[i-1])==TRUE))==TRUE){
  hhprofiles1$number1[i]<-hhprofiles1$number1[i-1]
  hhprofiles1$number2[i]<-hhprofiles1$number2[i-1]
  hhprofiles1$number3[i]<-hhprofiles1$number3[i-1]
  }else{
  hhprofiles1$number1[i]<-hhprofiles1$number1[i]
  hhprofiles1$number2[i]<-hhprofiles1$number2[i]
  hhprofiles1$number3[i]<-hhprofiles1$number3[i]
  }
}


### Re-assign ODD or EVEN after cleaning
### assign odd or even labels
hhprofiles1<-hhprofiles1%>%
  dplyr::mutate(oddeven=trunc(number1))
hhprofiles1$oddeven<-trunc(hhprofiles1$number1) ## truncate first number

for (i in 1:(nrow(hhprofiles1))){
  if ((hhprofiles1$oddeven[i]==0)==TRUE){
    hhprofiles1$isoddeven[i]<-"NA"
  }else if (is.even(hhprofiles1$oddeven[i])==TRUE){
    hhprofiles1$isoddeven[i]<-"EVEN"
  }else{
    hhprofiles1$isoddeven[i]<-"ODD"
  }
}

### meaningful breaks - predicting sequences (block ranges) - breaking the tie (MOTT ELIZABETH STREET) - extract those



```

